const restoList = [
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "347913",
          name: "Express By AB's",
          cloudinaryImageId:
            "FOOD_CATALOG/IMAGES/CMS/2026/3/31/ef34768d-47c1-46b4-a5da-063fc1743061_12ab775a-0abe-4ffa-a68b-f275913f2a43.jpg",
          locality: "Chinchwad",
          areaName: "Chinchwad",
          costForTwo: "₹300 for two",
          cuisines: ["North Indian", "Barbecue", "Kebabs", "Biryani"],
          avgRating: 4.2,
          parentId: "10320",
          avgRatingString: "4.2",
          totalRatingsString: "853",
          promoted: true,
          adTrackingId:
            "cid=2ac42318-6c93-40ec-bad1-223f3fe094f2~p=11~adgrpid=2ac42318-6c93-40ec-bad1-223f3fe094f2#ag1~mp=SWIGGY_IN~bl=FOOD~aet=RESTAURANT~aeid=347913~plpr=COLLECTION~eid=16e5aa65-3189-4562-acff-83cb39d5efdd~srvts=1778566346964~collid=83649",
          sla: {
            deliveryTime: 35,
            lastMileTravel: 1.1,
            serviceability: "SERVICEABLE",
            slaString: "30-40 mins",
            lastMileTravelString: "1.1 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseTime: "2026-05-12 23:00:00",
            opened: true,
          },
          badges: {},
          isOpen: true,
          type: "F",
          badgesV2: {
            entityBadges: {
              textBased: {},
              imageBased: {},
              textExtendedBadges: {},
            },
          },
          aggregatedDiscountInfoV3: {
            header: "55% OFF",
            discountTag: "FLAT DEAL",
          },
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
            commsStyling: {},
          },
          differentiatedUi: {
            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
            differentiatedUiMediaDetails: {
              mediaType: "ADS_MEDIA_ENUM_IMAGE",
              lottie: {},
              video: {},
            },
          },
          reviewsSummary: {},
          displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
          restaurantOfferPresentationInfo: {},
          externalRatings: {
            aggregatedRating: {
              rating: "4.2",
              ratingCount: "3.7K+",
            },
            source: "GOOGLE",
            sourceIconImageId: "v1704440323/google_ratings/rating_google_tag",
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
          campaignId: "2ac42318-6c93-40ec-bad1-223f3fe094f2",
          priceComparisonComms: {},
        },
        analytics: {},
        cta: {
          link: "swiggy://menu?restaurant_id=347913&source=collection&query=Biryani",
          text: "RESTAURANT_MENU",
          type: "DEEPLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food",
      },
      relevance: {
        type: "RELEVANCE_TYPE_ON_MENU_RETURN",
        sectionId: "MENU_RETURN_FOOD",
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "388111",
          name: "AB's - Absolute Barbecues",
          cloudinaryImageId:
            "FOOD_CATALOG/IMAGES/CMS/2025/10/17/28aedf7d-8a2b-477b-9c4c-5214e04f6691_29b6410c-b033-402d-917b-d76e342f5961.jpg",
          locality: "Chinchwad",
          areaName: "Chinchwad",
          costForTwo: "₹500 for two",
          cuisines: ["North Indian", "Barbecue", "Kebabs", "Biryani"],
          avgRating: 4.1,
          parentId: "387759",
          avgRatingString: "4.1",
          totalRatingsString: "1.4K+",
          promoted: true,
          adTrackingId:
            "cid=ac40f043-a119-4ac9-a9e8-c68ea9c344b6~p=12~adgrpid=ac40f043-a119-4ac9-a9e8-c68ea9c344b6#ag1~mp=SWIGGY_IN~bl=FOOD~aet=RESTAURANT~aeid=388111~plpr=COLLECTION~eid=8f63490c-e64b-4762-ad27-33d04a4d301b~srvts=1778566346964~collid=83649",
          sla: {
            deliveryTime: 32,
            lastMileTravel: 1.1,
            serviceability: "SERVICEABLE",
            slaString: "30-40 mins",
            lastMileTravelString: "1.1 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseTime: "2026-05-12 23:00:00",
            opened: true,
          },
          badges: {},
          isOpen: true,
          type: "F",
          badgesV2: {
            entityBadges: {
              textBased: {},
              imageBased: {},
              textExtendedBadges: {},
            },
          },
          aggregatedDiscountInfoV3: {
            header: "ITEMS",
            subHeader: "AT ₹17",
          },
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
            commsStyling: {},
          },
          differentiatedUi: {
            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
            differentiatedUiMediaDetails: {
              mediaType: "ADS_MEDIA_ENUM_IMAGE",
              lottie: {},
              video: {},
            },
          },
          reviewsSummary: {},
          displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
          restaurantOfferPresentationInfo: {},
          externalRatings: {
            aggregatedRating: {
              rating: "4.2",
              ratingCount: "3.7K+",
            },
            source: "GOOGLE",
            sourceIconImageId: "v1704440323/google_ratings/rating_google_tag",
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
          campaignId: "ac40f043-a119-4ac9-a9e8-c68ea9c344b6",
          priceComparisonComms: {},
        },
        analytics: {},
        cta: {
          link: "swiggy://menu?restaurant_id=388111&source=collection&query=Biryani",
          text: "RESTAURANT_MENU",
          type: "DEEPLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food",
      },
      relevance: {
        type: "RELEVANCE_TYPE_ON_MENU_RETURN",
        sectionId: "MENU_RETURN_FOOD",
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "970494",
          name: "Goila Butter Chicken",
          cloudinaryImageId: "qzq2734wagxspa67kqmv",
          locality: "NEHRU NAGAR,H BLOCK",
          areaName: "Pimpri",
          costForTwo: "₹600 for two",
          cuisines: ["Biryani", "Kebabs"],
          avgRating: 4.1,
          parentId: "322587",
          avgRatingString: "4.1",
          totalRatingsString: "714",
          promoted: true,
          adTrackingId:
            "cid=df2a594c-6e62-4a0a-8715-9d8088862def~p=14~adgrpid=df2a594c-6e62-4a0a-8715-9d8088862def#ag7~mp=SWIGGY_IN~bl=FOOD~aet=RESTAURANT~aeid=970494~plpr=COLLECTION~eid=efdcab0e-bd9b-4404-a863-7ecf1be179df~srvts=1778566346964~collid=83649",
          sla: {
            deliveryTime: 30,
            lastMileTravel: 1.8,
            serviceability: "SERVICEABLE",
            slaString: "25-30 mins",
            lastMileTravelString: "1.8 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseTime: "2026-05-12 23:00:00",
            opened: true,
          },
          badges: {
            imageBadges: [
              {
                imageId: "newg.png",
                description: "Gourmet",
              },
            ],
          },
          isOpen: true,
          type: "F",
          badgesV2: {
            entityBadges: {
              imageBased: {
                badgeObject: [
                  {
                    attributes: {
                      imageId: "newg.png",
                      description: "Gourmet",
                      theme: "",
                    },
                  },
                ],
              },
              textExtendedBadges: {},
              textBased: {},
            },
          },
          aggregatedDiscountInfoV3: {
            header: "₹125 OFF",
            subHeader: "ABOVE ₹249",
            discountTag: "FLAT DEAL",
          },
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
            commsStyling: {},
          },
          differentiatedUi: {
            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
            differentiatedUiMediaDetails: {
              mediaType: "ADS_MEDIA_ENUM_IMAGE",
              lottie: {},
              video: {},
            },
          },
          reviewsSummary: {},
          displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
          restaurantOfferPresentationInfo: {},
          externalRatings: {
            aggregatedRating: {
              rating: "--",
            },
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
          campaignId: "df2a594c-6e62-4a0a-8715-9d8088862def",
          priceComparisonComms: {},
        },
        analytics: {},
        cta: {
          link: "swiggy://menu?restaurant_id=970494&source=collection&query=Biryani",
          text: "RESTAURANT_MENU",
          type: "DEEPLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food",
      },
      relevance: {
        type: "RELEVANCE_TYPE_ON_MENU_RETURN",
        sectionId: "MENU_RETURN_FOOD",
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "399563",
          name: "The Good Bowl",
          cloudinaryImageId:
            "RX_THUMBNAIL/IMAGES/VENDOR/2024/11/15/69a2bc92-4ac6-4c3f-85cd-2bd0a0e8fdd4_399563.jpg",
          locality: "Chinchwad",
          areaName: "Nigdi",
          costForTwo: "₹400 for two",
          cuisines: ["Biryani", "Pastas", "Punjabi", "Desserts", "Beverages"],
          avgRating: 4.3,
          parentId: "7918",
          avgRatingString: "4.3",
          totalRatingsString: "1.4K+",
          sla: {
            deliveryTime: 31,
            lastMileTravel: 1.8,
            serviceability: "SERVICEABLE",
            slaString: "30-35 mins",
            lastMileTravelString: "1.8 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseTime: "2026-05-12 23:59:00",
            opened: true,
          },
          badges: {},
          isOpen: true,
          type: "F",
          badgesV2: {
            entityBadges: {
              textBased: {},
              imageBased: {},
              textExtendedBadges: {},
            },
          },
          aggregatedDiscountInfoV3: {
            header: "ITEMS",
            subHeader: "AT ₹129",
          },
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
            commsStyling: {},
          },
          differentiatedUi: {
            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
            differentiatedUiMediaDetails: {
              mediaType: "ADS_MEDIA_ENUM_IMAGE",
              lottie: {},
              video: {},
            },
          },
          reviewsSummary: {},
          displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
          restaurantOfferPresentationInfo: {},
          externalRatings: {
            aggregatedRating: {
              rating: "--",
            },
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
          priceComparisonComms: {},
        },
        analytics: {},
        cta: {
          link: "swiggy://menu?restaurant_id=399563&source=collection&query=Biryani",
          text: "RESTAURANT_MENU",
          type: "DEEPLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food",
      },
      relevance: {
        type: "RELEVANCE_TYPE_ON_MENU_RETURN",
        sectionId: "MENU_RETURN_FOOD",
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "399564",
          name: "The Biryani Life",
          cloudinaryImageId: "ayso4ezeqeb6dn37klhk",
          locality: "Chinchwad",
          areaName: "Nigdi",
          costForTwo: "₹250 for two",
          cuisines: [
            "Biryani",
            "Mughlai",
            "Lucknowi",
            "Hyderabadi",
            "Kebabs",
            "Desserts",
            "Beverages",
          ],
          avgRating: 4,
          parentId: "8496",
          avgRatingString: "4.0",
          totalRatingsString: "878",
          sla: {
            deliveryTime: 28,
            lastMileTravel: 1.8,
            serviceability: "SERVICEABLE",
            slaString: "25-30 mins",
            lastMileTravelString: "1.8 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseTime: "2026-05-12 23:59:00",
            opened: true,
          },
          badges: {},
          isOpen: true,
          type: "F",
          badgesV2: {
            entityBadges: {
              textBased: {},
              imageBased: {},
              textExtendedBadges: {},
            },
          },
          aggregatedDiscountInfoV3: {
            header: "ITEMS",
            subHeader: "AT ₹99",
          },
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
            commsStyling: {},
          },
          differentiatedUi: {
            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
            differentiatedUiMediaDetails: {
              mediaType: "ADS_MEDIA_ENUM_IMAGE",
              lottie: {},
              video: {},
            },
          },
          reviewsSummary: {},
          displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
          restaurantOfferPresentationInfo: {},
          externalRatings: {
            aggregatedRating: {
              rating: "--",
            },
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
          priceComparisonComms: {},
        },
        analytics: {},
        cta: {
          link: "swiggy://menu?restaurant_id=399564&source=collection&query=Biryani",
          text: "RESTAURANT_MENU",
          type: "DEEPLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food",
      },
      relevance: {
        type: "RELEVANCE_TYPE_ON_MENU_RETURN",
        sectionId: "MENU_RETURN_FOOD",
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "1109395",
          name: "Burger Singh(Big Punjabi Burgers)",
          cloudinaryImageId:
            "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/6/9d8103e7-79fc-4ae9-8812-b49c51a60605_1109395.jpg",
          locality: "NEAR KALIKA MATA TEMPLE,Chinchwad,Pimpri Chinchwad",
          areaName: "Elpro City Square",
          costForTwo: "₹300 for two",
          cuisines: [
            "Burgers",
            "Snacks",
            "Desserts",
            "Beverages",
            "Fast Food",
            "American",
            "Indian",
            "Biryani",
          ],
          avgRating: 4.1,
          parentId: "772431",
          avgRatingString: "4.1",
          totalRatingsString: "717",
          sla: {
            deliveryTime: 31,
            lastMileTravel: 2.2,
            serviceability: "SERVICEABLE",
            slaString: "30-35 mins",
            lastMileTravelString: "2.2 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseTime: "2026-05-13 00:00:00",
            opened: true,
          },
          badges: {},
          isOpen: true,
          type: "F",
          badgesV2: {
            entityBadges: {
              textExtendedBadges: {},
              textBased: {},
              imageBased: {},
            },
          },
          aggregatedDiscountInfoV3: {
            header: "50% OFF",
            discountTag: "FLAT DEAL",
          },
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
            commsStyling: {},
          },
          differentiatedUi: {
            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
            differentiatedUiMediaDetails: {
              mediaType: "ADS_MEDIA_ENUM_IMAGE",
              lottie: {},
              video: {},
            },
          },
          reviewsSummary: {},
          displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
          restaurantOfferPresentationInfo: {},
          externalRatings: {
            aggregatedRating: {
              rating: "--",
            },
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
          priceComparisonComms: {},
        },
        analytics: {},
        cta: {
          link: "swiggy://menu?restaurant_id=1109395&source=collection&query=Biryani",
          text: "RESTAURANT_MENU",
          type: "DEEPLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food",
      },
      relevance: {
        type: "RELEVANCE_TYPE_ON_MENU_RETURN",
        sectionId: "MENU_RETURN_FOOD",
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "399562",
          name: "LunchBox - Meals and Thalis",
          cloudinaryImageId:
            "RX_THUMBNAIL/IMAGES/VENDOR/2024/10/16/3d1f65f1-a259-440f-968c-ff558d22722f_399562.jpg",
          locality: "Chinchwad",
          areaName: "Nigdi",
          costForTwo: "₹200 for two",
          cuisines: ["Thalis", "North Indian", "Biryani"],
          avgRating: 4.2,
          parentId: "4925",
          avgRatingString: "4.2",
          totalRatingsString: "2.2K+",
          sla: {
            deliveryTime: 29,
            lastMileTravel: 1.8,
            serviceability: "SERVICEABLE",
            slaString: "25-30 mins",
            lastMileTravelString: "1.8 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseTime: "2026-05-12 23:59:00",
            opened: true,
          },
          badges: {
            imageBadges: [
              {
                imageId: "Health%20Hub/RX%20BADGE/BADGE2.png",
                description: "EatRight",
              },
            ],
          },
          isOpen: true,
          type: "F",
          badgesV2: {
            entityBadges: {
              textExtendedBadges: {},
              textBased: {},
              imageBased: {
                badgeObject: [
                  {
                    attributes: {
                      imageId: "Health%20Hub/RX%20BADGE/BADGE2.png",
                      description: "EatRight",
                      theme: "",
                    },
                  },
                ],
              },
            },
          },
          aggregatedDiscountInfoV3: {
            header: "ITEMS",
            subHeader: "AT ₹99",
            logoCtx: {
              text: "BENEFITS",
            },
          },
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
            commsStyling: {},
          },
          differentiatedUi: {
            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
            differentiatedUiMediaDetails: {
              mediaType: "ADS_MEDIA_ENUM_IMAGE",
              lottie: {},
              video: {},
            },
          },
          reviewsSummary: {},
          displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
          restaurantOfferPresentationInfo: {},
          externalRatings: {
            aggregatedRating: {
              rating: "--",
            },
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
          priceComparisonComms: {},
        },
        analytics: {},
        cta: {
          link: "swiggy://menu?restaurant_id=399562&source=collection&query=Biryani",
          text: "RESTAURANT_MENU",
          type: "DEEPLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food",
      },
      relevance: {
        type: "RELEVANCE_TYPE_ON_MENU_RETURN",
        sectionId: "MENU_RETURN_FOOD",
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "1029568",
          name: "ZAZA Mughal Biryani",
          cloudinaryImageId:
            "RX_THUMBNAIL/IMAGES/VENDOR/2025/1/20/a982bc6c-7fb9-477c-909e-6864cd104106_1029568.jpg",
          locality: "Chinchwad",
          areaName: "Near Kalika Mata Temple",
          costForTwo: "₹250 for two",
          cuisines: ["Biryani", "Awadhi"],
          avgRating: 4.5,
          parentId: "22473",
          avgRatingString: "4.5",
          totalRatingsString: "194",
          sla: {
            deliveryTime: 25,
            lastMileTravel: 1.9,
            serviceability: "SERVICEABLE",
            slaString: "20-30 mins",
            lastMileTravelString: "1.9 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseTime: "2026-05-13 02:00:00",
            opened: true,
          },
          badges: {
            imageBadges: [
              {
                imageId:
                  "brand_cards/Badges%202026/39_Best%20in%20Biryani2026.png",
                description: "Best in Biryani",
              },
              {
                imageId:
                  "brand_cards/Badges%202026/67_Best%20in%20Mughlai2026.png",
                description: "Best in Mughlai",
              },
            ],
          },
          isOpen: true,
          type: "F",
          badgesV2: {
            entityBadges: {
              imageBased: {
                badgeObject: [
                  {
                    attributes: {
                      imageId:
                        "brand_cards/Badges%202026/39_Best%20in%20Biryani2026.png",
                      description: "Best in Biryani",
                      theme: "",
                    },
                  },
                  {
                    attributes: {
                      theme: "",
                      imageId:
                        "brand_cards/Badges%202026/67_Best%20in%20Mughlai2026.png",
                      description: "Best in Mughlai",
                    },
                  },
                ],
              },
              textExtendedBadges: {},
              textBased: {},
            },
          },
          aggregatedDiscountInfoV3: {
            header: "ITEMS",
            subHeader: "AT ₹129",
          },
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
            commsStyling: {},
          },
          differentiatedUi: {
            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
            differentiatedUiMediaDetails: {
              mediaType: "ADS_MEDIA_ENUM_IMAGE",
              lottie: {},
              video: {},
            },
          },
          reviewsSummary: {},
          displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
          restaurantOfferPresentationInfo: {},
          externalRatings: {
            aggregatedRating: {
              rating: "--",
            },
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
          priceComparisonComms: {},
        },
        analytics: {},
        cta: {
          link: "swiggy://menu?restaurant_id=1029568&source=collection&query=Biryani",
          text: "RESTAURANT_MENU",
          type: "DEEPLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food",
      },
      relevance: {
        type: "RELEVANCE_TYPE_ON_MENU_RETURN",
        sectionId: "MENU_RETURN_FOOD",
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "1029564",
          name: "BOX8 - Desi Meals",
          cloudinaryImageId:
            "RX_THUMBNAIL/IMAGES/VENDOR/2025/3/26/4523a420-6e0c-429b-bcde-6e33e1b38d6e_1029564.jpg",
          locality: "Chinchwad",
          areaName: "Near Kalika Mata Temple",
          costForTwo: "₹200 for two",
          cuisines: ["Biryani", "Thalis", "Home Food"],
          avgRating: 4.4,
          parentId: "10655",
          avgRatingString: "4.4",
          totalRatingsString: "660",
          sla: {
            deliveryTime: 25,
            lastMileTravel: 1.9,
            serviceability: "SERVICEABLE",
            slaString: "20-30 mins",
            lastMileTravelString: "1.9 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseTime: "2026-05-13 02:00:00",
            opened: true,
          },
          badges: {
            imageBadges: [
              {
                imageId:
                  "brand_cards/Badges%202026/26_Best%20in%20North%20Indian2026.png",
                description: "Best in North Indian",
              },
              {
                imageId:
                  "brand_cards/Badges%202026/67_Best%20in%20Mughlai2026.png",
                description: "Best in Mughlai",
              },
              {
                imageId:
                  "brand_cards/Badges%202026/85_Best%20in%20Corporate2026.png",
                description: "Best in Corporate",
              },
            ],
          },
          isOpen: true,
          type: "F",
          badgesV2: {
            entityBadges: {
              imageBased: {
                badgeObject: [
                  {
                    attributes: {
                      imageId:
                        "brand_cards/Badges%202026/26_Best%20in%20North%20Indian2026.png",
                      description: "Best in North Indian",
                      theme: "",
                    },
                  },
                  {
                    attributes: {
                      description: "Best in Mughlai",
                      theme: "",
                      imageId:
                        "brand_cards/Badges%202026/67_Best%20in%20Mughlai2026.png",
                    },
                  },
                  {
                    attributes: {
                      imageId:
                        "brand_cards/Badges%202026/85_Best%20in%20Corporate2026.png",
                      description: "Best in Corporate",
                      theme: "",
                    },
                  },
                ],
              },
              textExtendedBadges: {},
              textBased: {},
            },
          },
          aggregatedDiscountInfoV3: {
            header: "ITEMS",
            subHeader: "AT ₹99",
          },
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
            commsStyling: {},
          },
          differentiatedUi: {
            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
            differentiatedUiMediaDetails: {
              mediaType: "ADS_MEDIA_ENUM_IMAGE",
              lottie: {},
              video: {},
            },
          },
          reviewsSummary: {},
          displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
          restaurantOfferPresentationInfo: {},
          externalRatings: {
            aggregatedRating: {
              rating: "--",
            },
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
          priceComparisonComms: {},
        },
        analytics: {},
        cta: {
          link: "swiggy://menu?restaurant_id=1029564&source=collection&query=Biryani",
          text: "RESTAURANT_MENU",
          type: "DEEPLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food",
      },
      relevance: {
        type: "RELEVANCE_TYPE_ON_MENU_RETURN",
        sectionId: "MENU_RETURN_FOOD",
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "399558",
          name: "Behrouz Biryani",
          cloudinaryImageId: "a4ffed13eb197c6df43dfe1c756560e5",
          locality: "Chinchwad",
          areaName: "Nigdi",
          costForTwo: "₹500 for two",
          cuisines: [
            "Biryani",
            "North Indian",
            "Kebabs",
            "Mughlai",
            "Beverages",
            "Desserts",
          ],
          avgRating: 4.1,
          parentId: "1803",
          avgRatingString: "4.1",
          totalRatingsString: "3.1K+",
          sla: {
            deliveryTime: 33,
            lastMileTravel: 1.8,
            serviceability: "SERVICEABLE",
            slaString: "30-40 mins",
            lastMileTravelString: "1.8 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseTime: "2026-05-12 23:59:00",
            opened: true,
          },
          badges: {
            imageBadges: [
              {
                imageId:
                  "brand_cards/Badges%202026/53_Best%20in%20Gourmet2026.png",
                description: "Best in Gourmet",
              },
              {
                imageId: "newg.png",
                description: "Gourmet",
              },
            ],
          },
          isOpen: true,
          type: "F",
          badgesV2: {
            entityBadges: {
              imageBased: {
                badgeObject: [
                  {
                    attributes: {
                      imageId:
                        "brand_cards/Badges%202026/53_Best%20in%20Gourmet2026.png",
                      description: "Best in Gourmet",
                      theme: "",
                    },
                  },
                  {
                    attributes: {
                      theme: "",
                      imageId: "newg.png",
                      description: "Gourmet",
                    },
                  },
                ],
              },
              textExtendedBadges: {},
              textBased: {},
            },
          },
          aggregatedDiscountInfoV3: {
            header: "ITEMS",
            subHeader: "AT ₹99",
          },
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
            commsStyling: {},
          },
          differentiatedUi: {
            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
            differentiatedUiMediaDetails: {
              mediaType: "ADS_MEDIA_ENUM_IMAGE",
              lottie: {},
              video: {},
            },
          },
          reviewsSummary: {},
          displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
          restaurantOfferPresentationInfo: {},
          externalRatings: {
            aggregatedRating: {
              rating: "--",
            },
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
          priceComparisonComms: {},
        },
        analytics: {},
        cta: {
          link: "swiggy://menu?restaurant_id=399558&source=collection&query=Biryani",
          text: "RESTAURANT_MENU",
          type: "DEEPLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food",
      },
      relevance: {
        type: "RELEVANCE_TYPE_ON_MENU_RETURN",
        sectionId: "MENU_RETURN_FOOD",
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "53036",
          name: "Kolhapuri Pahunchar",
          cloudinaryImageId: "zjn1qwx7mjfc47bnmrzz",
          locality: "Chinchwad",
          areaName: "Chinchwad",
          costForTwo: "₹400 for two",
          cuisines: [
            "Maharashtrian",
            "Biryani",
            "Thalis",
            "North Indian",
            "Chinese",
            "Indian",
            "Mughlai",
            "Malwani",
            "Kebabs",
            "Beverages",
          ],
          avgRating: 4.1,
          parentId: "119810",
          avgRatingString: "4.1",
          totalRatingsString: "7.6K+",
          sla: {
            deliveryTime: 33,
            lastMileTravel: 1.4,
            serviceability: "SERVICEABLE",
            slaString: "30-35 mins",
            lastMileTravelString: "1.4 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseTime: "2026-05-12 15:30:00",
            opened: true,
          },
          badges: {
            imageBadges: [
              {
                imageId:
                  "brand_cards/Badges%202026/48_Best%20in%20Coastal2026.png",
                description: "Best in Coastal",
              },
            ],
          },
          isOpen: true,
          type: "F",
          badgesV2: {
            entityBadges: {
              imageBased: {
                badgeObject: [
                  {
                    attributes: {
                      theme: "",
                      imageId:
                        "brand_cards/Badges%202026/48_Best%20in%20Coastal2026.png",
                      description: "Best in Coastal",
                    },
                  },
                ],
              },
              textExtendedBadges: {},
              textBased: {},
            },
          },
          aggregatedDiscountInfoV3: {
            header: "ITEMS",
            subHeader: "AT ₹39",
          },
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
            commsStyling: {},
          },
          differentiatedUi: {
            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
            differentiatedUiMediaDetails: {
              mediaType: "ADS_MEDIA_ENUM_IMAGE",
              lottie: {},
              video: {},
            },
          },
          reviewsSummary: {},
          displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
          restaurantOfferPresentationInfo: {},
          externalRatings: {
            aggregatedRating: {
              rating: "4.0",
              ratingCount: "3.1K+",
            },
            source: "GOOGLE",
            sourceIconImageId: "v1704440323/google_ratings/rating_google_tag",
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
          priceComparisonComms: {},
        },
        analytics: {},
        cta: {
          link: "swiggy://menu?restaurant_id=53036&source=collection&query=Biryani",
          text: "RESTAURANT_MENU",
          type: "DEEPLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food",
      },
      relevance: {
        type: "RELEVANCE_TYPE_ON_MENU_RETURN",
        sectionId: "MENU_RETURN_FOOD",
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "39774",
          name: "Chawadi",
          cloudinaryImageId: "2e3629a24061085fb079f033a455c878",
          locality: "Chinchwad",
          areaName: "Chinchwad",
          costForTwo: "₹400 for two",
          cuisines: ["North Indian", "Chinese", "Seafood", "Punjabi"],
          avgRating: 4.3,
          parentId: "58827",
          avgRatingString: "4.3",
          totalRatingsString: "29K+",
          sla: {
            deliveryTime: 35,
            lastMileTravel: 1.1,
            serviceability: "SERVICEABLE",
            slaString: "30-35 mins",
            lastMileTravelString: "1.1 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseTime: "2026-05-12 16:00:00",
            opened: true,
          },
          badges: {},
          isOpen: true,
          type: "F",
          badgesV2: {
            entityBadges: {
              textBased: {},
              imageBased: {},
              textExtendedBadges: {},
            },
          },
          aggregatedDiscountInfoV3: {
            header: "ITEMS",
            subHeader: "AT ₹33",
            logoCtx: {
              text: "BENEFITS",
            },
          },
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
            commsStyling: {},
          },
          differentiatedUi: {
            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
            differentiatedUiMediaDetails: {
              mediaType: "ADS_MEDIA_ENUM_IMAGE",
              lottie: {},
              video: {},
            },
          },
          reviewsSummary: {},
          displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
          restaurantOfferPresentationInfo: {},
          externalRatings: {
            aggregatedRating: {
              rating: "3.9",
              ratingCount: "3.3K+",
            },
            source: "GOOGLE",
            sourceIconImageId: "v1704440323/google_ratings/rating_google_tag",
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
          priceComparisonComms: {},
        },
        analytics: {},
        cta: {
          link: "swiggy://menu?restaurant_id=39774&source=collection&query=Biryani",
          text: "RESTAURANT_MENU",
          type: "DEEPLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food",
      },
      relevance: {
        type: "RELEVANCE_TYPE_ON_MENU_RETURN",
        sectionId: "MENU_RETURN_FOOD",
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "954313",
          name: "Bikkgane Biryani",
          cloudinaryImageId:
            "FOOD_CATALOG/IMAGES/CMS/2025/6/24/28ba8630-7acf-4c97-b653-67acbd83b535_6b97bc3b-ddf2-476d-9849-aa8b0e0e7856.jpg",
          locality: "Sai Vaastu Heights",
          areaName: "Pimple Saudagar",
          costForTwo: "₹350 for two",
          cuisines: [
            "Biryani",
            " Hyderabadi",
            " Andhra",
            " Lucknowi",
            " Kolkata",
            " Desserts",
            "Beverages",
          ],
          avgRating: 4.2,
          parentId: "5070",
          avgRatingString: "4.2",
          totalRatingsString: "2.5K+",
          sla: {
            deliveryTime: 40,
            lastMileTravel: 6.3,
            serviceability: "SERVICEABLE",
            slaString: "35-45 mins",
            lastMileTravelString: "6.3 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseTime: "2026-05-13 00:00:00",
            opened: true,
          },
          badges: {
            imageBadges: [
              {
                imageId:
                  "brand_cards/Badges%202026/39_Best%20in%20Biryani2026.png",
                description: "Best in Biryani",
              },
              {
                imageId:
                  "brand_cards/Badges%202026/85_Best%20in%20Corporate2026.png",
                description: "Best in Corporate",
              },
            ],
          },
          isOpen: true,
          type: "F",
          badgesV2: {
            entityBadges: {
              textBased: {},
              imageBased: {
                badgeObject: [
                  {
                    attributes: {
                      description: "Best in Biryani",
                      theme: "",
                      imageId:
                        "brand_cards/Badges%202026/39_Best%20in%20Biryani2026.png",
                    },
                  },
                  {
                    attributes: {
                      description: "Best in Corporate",
                      theme: "",
                      imageId:
                        "brand_cards/Badges%202026/85_Best%20in%20Corporate2026.png",
                    },
                  },
                ],
              },
              textExtendedBadges: {},
            },
          },
          aggregatedDiscountInfoV3: {
            header: "50% OFF",
            discountTag: "FLAT DEAL",
          },
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
            commsStyling: {},
          },
          differentiatedUi: {
            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
            differentiatedUiMediaDetails: {
              mediaType: "ADS_MEDIA_ENUM_IMAGE",
              lottie: {},
              video: {},
            },
          },
          reviewsSummary: {},
          displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
          restaurantOfferPresentationInfo: {},
          externalRatings: {
            aggregatedRating: {
              rating: "--",
            },
          },
          ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
          priceComparisonComms: {},
        },
        analytics: {},
        cta: {
          link: "swiggy://menu?restaurant_id=954313&source=collection&query=Biryani",
          text: "RESTAURANT_MENU",
          type: "DEEPLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food",
      },
      relevance: {
        type: "RELEVANCE_TYPE_ON_MENU_RETURN",
        sectionId: "MENU_RETURN_FOOD",
      },
    },
  },
];

export default restoList;